map dT shell mv %s /home/${USER}/.local/share/Trash/files/
map - cd ..
# set preview_images true
set preview_images true
set preview_images_method ueberzug
# set preview_images_method kitty
# Použij scope.sh pro preview
# set use_preview_script true
# set preview_script ~/.config/ranger/scope.sh

# set preview_images_method sixel
# set preview_images_method custom
# set preview_images_script ~/.config/ranger/scope_scripts/ueberzugpp_preview.py
set draw_borders true

